openapi: 3.0.0
info:
  title: APOD Service
  version: 1.0.0
  description: A service to fetch APOD images and metadata.

servers:
  - url: "http://localhost:8080"

paths:
  /api/pictures:
    get:
      summary: Get all entries in the album
      parameters:
        - name: offset
          in: query
          description: The offset for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          description: The number of entries to return
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '429':
          description: Too many requests
          content:
            application/json:
              example:
                message: "Too Many Requests"
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                "limit": 1
                "offset": 0
                "apods":
                  - copyright: "Bastian Werner"
                    date: "2023-12-20"
                    explanation: "What's causing those unusual sky arcs? Ice crystals.  While crossing a field of fresh snow near Füssen, Bavaria, Germany, earlier this month, the photographer noticed that he had entered an ice fog.  For suspended water to freeze into an ice fog requires quite cold temperatures, and indeed the air temperature on this day was measured at well below zero.  The ice fog reflected light from the Sun setting behind St. Coleman Church.  The result was one of the greatest spectacles the photographer has ever seen. First, the spots in the featured picture are not background stars but suspended ice and snow. Next, two prominent ice halos are visible: the 22-degree halo and the 46-degree halo. Multiple arcs are also visible, including, from top to bottom, antisolar (subsun), circumzenithal, Parry, tangent, and parhelic (horizontal). Finally, the balloon shaped curve connecting the top arc to the Sun is the rarest of all: it is the heliac arc, created by reflection from the sides of hexagonally shaped ice crystals suspended in a horizontal orientation."
                    media_type: "image"
                    service_version: "v1"
                    title: "Ice Halos over Bavaria"
                    url: "https://apod.nasa.gov/apod/image/2312/BavarianHalos_Werner_960.jpg"
                    hdurl: "https://apod.nasa.gov/apod/image/2312/BavarianHalos_Werner_1500.jpg"
                    data: "b5QMRP0joxQnyN1v40Rp0x1adPybIpdOFqhad4LrD95aqtpG2urU0tVwRRRK0r8VpTtdSsWXPsN44BpCUN+vGcdE6NPl7b8WqcWl/dcknAMOwjhEqrYtFVcQ2lTZ3vZjrUGQ07W61iq1YLjzTVLgnaPvPajiIMtBXwecDHcpbb/wCKaezw5UxVBezdOfNO2n2hnebDZVP20Kmh1siPzh0Zaq9txUKGRPy7LflbObx2MS7ijy+P+A9Tl6YPmUnBV+iU8dWk6+S/JHzsj3rFoBn/AHO39xduP3D49wGjsFbKdhL4sDFJwN2BCI1iKJmBFZNiZHH6dPIMxCL2dv60v8zq+7HPHM5KlF+Nh7/1ZlqxslWA2sDqUvVseLNtPPLLOPMsrcLIMxaYuPGIcf0yp/"


  /api/picture/{date}:
    get:
      summary: Get entry for a specific date
      parameters:
        - name: date
          in: path
          required: true
          description: The date for the entry in the format YYYY-MM-DD
          schema:
            type: string
      responses:
        '429':
          description: Too many requests
          content:
            application/json:
              example:
                message: "Too Many Requests"
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                copyright: "Bastian Werner"
                date: "2023-12-20"
                explanation: "What's causing those unusual sky arcs? Ice crystals.  While crossing a field of fresh snow near Füssen, Bavaria, Germany, earlier this month, the photographer noticed that he had entered an ice fog.  For suspended water to freeze into an ice fog requires quite cold temperatures, and indeed the air temperature on this day was measured at well below zero.  The ice fog reflected light from the Sun setting behind St. Coleman Church.  The result was one of the greatest spectacles the photographer has ever seen. First, the spots in the featured picture are not background stars but suspended ice and snow. Next, two prominent ice halos are visible: the 22-degree halo and the 46-degree halo. Multiple arcs are also visible, including, from top to bottom, antisolar (subsun), circumzenithal, Parry, tangent, and parhelic (horizontal). Finally, the balloon shaped curve connecting the top arc to the Sun is the rarest of all: it is the heliac arc, created by reflection from the sides of hexagonally shaped ice crystals suspended in a horizontal orientation."
                media_type: "image"
                service_version: "v1"
                title: "Ice Halos over Bavaria"
                url: "https://apod.nasa.gov/apod/image/2312/BavarianHalos_Werner_960.jpg"
                hdurl: "https://apod.nasa.gov/apod/image/2312/BavarianHalos_Werner_1500.jpg"
                data: "b5QMRP0joxQnyN1v40Rp0x1adPybIpdOFqhad4LrD95aqtpG2urU0tVwRRRK0r8VpTtdSsWXPsN44BpCUN+vGcdE6NPl7b8WqcWl/dcknAMOwjhEqrYtFVcQ2lTZ3vZjrUGQ07W61iq1YLjzTVLgnaPvPajiIMtBXwecDHcpbb/wCKaezw5UxVBezdOfNO2n2hnebDZVP20Kmh1siPzh0Zaq9txUKGRPy7LflbObx2MS7ijy+P+A9Tl6YPmUnBV+iU8dWk6+S/JHzsj3rFoBn/AHO39xduP3D49wGjsFbKdhL4sDFJwN2BCI1iKJmBFZNiZHH6dPIMxCL2dv60v8zq+7HPHM5KlF+Nh7/1ZlqxslWA2sDqUvVseLNtPPLLOPMsrcLIMxaYuPGIcf0yp/"

